const path = require("path");
require("dotenv").config({ path: path.join(__dirname, "../.env") });
const { Octokit } = require("@octokit/rest");
const fs = require("fs");

const octokit = new Octokit({
  auth: process.env.GITHUB_TOKEN,
});

const OWNER = "moshams272";
const REPO = "test-webpack-docs";
const BASE_BRANCH = "main";
const NEW_BRANCH = `docs-update-${Date.now()}`;

const packageJsonPath = path.join(__dirname, "../package.json");
const packageData = JSON.parse(fs.readFileSync(packageJsonPath, "utf-8"));
const majorVersion = packageData.version.split(".")[0];
const versionFolder = `v${majorVersion}`;

function getAllFiles(dirPath, arrayOfFiles = []) {
  const files = fs.readdirSync(dirPath);

  files.forEach((file) => {
    const fullPath = path.join(dirPath, file);
    if (fs.statSync(fullPath).isDirectory()) {
      arrayOfFiles = getAllFiles(fullPath, arrayOfFiles);
    } else {
      arrayOfFiles.push(fullPath);
    }
  });

  return arrayOfFiles;
}

async function createPullRequest() {
  try {
    console.log("Retrieving latest commit from the base branch...");
    const { data: refData } = await octokit.git.getRef({
      owner: OWNER,
      repo: REPO,
      ref: `heads/${BASE_BRANCH}`,
    });
    const latestCommitSha = refData.object.sha;

    const { data: commitData } = await octokit.git.getCommit({
      owner: OWNER,
      repo: REPO,
      commit_sha: latestCommitSha,
    });
    const baseTreeSha = commitData.tree.sha;

    const docsDir = path.join(__dirname, `../docs/${versionFolder}/api`);
    const allFiles = getAllFiles(docsDir);
    const treeItems = [];

    for (const filePath of allFiles) {
      if (filePath.endsWith(".mdx")) {
        const content = fs.readFileSync(filePath, "utf-8");
        const relativePath = path.relative(docsDir, filePath).replace(/\\/g, '/');

        treeItems.push({
          path: `docs/${versionFolder}/api/${relativePath}`,
          mode: "100644",
          type: "blob",
          content: content,
        });
      }
    }

    if (treeItems.length === 0) {
      console.log("There is no MDX files to upload!");
      return;
    }

    console.log("Creating a new tree with the generated MDX files...");
    const { data: treeData } = await octokit.git.createTree({
      owner: OWNER,
      repo: REPO,
      base_tree: baseTreeSha,
      tree: treeItems,
    });

    console.log("Commiting the new tree...");
    const { data: newCommitData } = await octokit.git.createCommit({
      owner: OWNER,
      repo: REPO,
      message: "feat: auto-generate MDX API documentation from JSDoc",
      tree: treeData.sha,
      parents: [latestCommitSha],
    });

    console.log("Creating new branch...");
    await octokit.git.createRef({
      owner: OWNER,
      repo: REPO,
      ref: `refs/heads/${NEW_BRANCH}`,
      sha: newCommitData.sha,
    });

    console.log("Opening Pull Request...");
    const { data: prData } = await octokit.pulls.create({
      owner: OWNER,
      repo: REPO,
      title: `Automated API Docs Generation for ${versionFolder}`,
      body: "This PR is automatically generated by our Node.js script for Milestone 1.",
      head: NEW_BRANCH,
      base: BASE_BRANCH,
    });

    console.log(`Pull Request created successfully!`);
    console.log(`PR URL: ${prData.html_url}`);

  } catch (error) {
    console.error("Error creating Pull Request: ", error.message);
  }
}

createPullRequest();